version: '3'
volumes:
  build_db_data:
  build_app_data:

services:
  mysql_build:
    image: mysql:5.6.40
    restart: always
    ports:
      - "13306:13306"
    volumes:
      - build_db_data:/var/lib/mysql
      - ./docker-compose-files/pageonex.cnf:/etc/mysql/conf.d/pageonex.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dc-dev

  app_build:
    build: .
    environment:
      - RAILS_ENV=development
      - DATABASE_ADAPTER=mysql2
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=mysql_build
      - DATABASE_PORT=13306
      - DATABASE_NAME=dc-dev
    depends_on:
      - "mysql_build"
    ports:
      - '3000:3000'
    links:
      - "mysql_build"
    volumes:
      - build_app_data:/workspace
      - ./docker-compose-files/wrap-start-app.sh:/usr/local/bin/wrap-start-app.sh
    command:
      - wrap-start-app.sh
      - mysql_build
      - root
      - "bundle exec puma -C config/puma.rb"
